# General {-}

> Everyone you meet is fighting a battle you know nothing about. Be kind. Always.

From *Skam*

> Friendship means little when it's convenient.

From *John Wick 4*

> It is also possible to paint a house with a toothbrush!

Daniel Nebdal, on a Cancer Genetics Department meeting, where he was presenting the new Research Portal (IT infrastructure) in Oslo's University Hospital.
Very deep quote.
So much effort is being spent for useless/inefficient/meaningless things.

> It is easier to get friends when you are younger.

Kapustin, *Conversations with Nikolai Kapustin*

Kapustin here was referring to his teenage years when he was at the Musical College in Moscow.
This phrase rings so true.

> Faking intelligence is intelligence. And you can only fake it if you have it!

*Judea Pearl* - [interview](https://www.youtube.com/watch?v=pEBI0vF45ic) with Lex Friedman

> Time slows if you are moving fast.

I read this in an article from the Quanta magazine where the author was describing the paradox of Alice and Bob, related to Einstein's theories of relativity.
That is, Alice leaves Earth with a speceship, traveling at the speed of light.
She returns a few months later, only to find Bob having aged years!
Tragic!
Despite the story, it is a really nice phrase to say, since it connects with other theories of Life!

> The most beautiful and precious things in this world cannot be heard or seen, but only felt by the heart.

From a Korean movie, *Silence (2011)*.
Quote is from *Helen Keller*.

> Work expands so as to fill the time available for its completion.

*Parkison's Law*

> Anything that can go wrong will go wrong.

*Murphy's Law* (saw it first time in the movie Interstellar)

> A man got to be what he is Joey. Can't break the mold.

From *Shane (1953)*. Shane teeling Joey he can't stay. Has to move on.

> Any treasure you attain without anyone ever working, is no treasure at all.

Chief Nyanta, Log Horizon

> The trick to being a scientist is to be open to using a wide variety of tools

*Leo Breiman*, from the paper *Statistical modeling: The two cultures (2001)*

> I didn't receive any email. Not sure how that might have happened, but electrons are small and easy to lose sometimes.

*Will Murray*

> It's been real. It's been good. It ain't been real good.

From [Obama and Luther’s Farewell Address](https://youtu.be/n2svSvVF_F0?t=210) - Key & Peele

> The nature of promises is that they stay immune to changing circumstances.

Kevin Spacey as Francis Underwood in *House of Cards*

> To create is to limit oneself.

*Alexander Scriabin*

The objects created via our imagination can take abstract representations in our world throught various forms of art, e.g. music, painting, poems, movies, etc.
Note though, that these are only approximations of the originals and as such, no matter how best the art form represents the mental images/stories/configurations, they can never hope to match them (and as such, they limit them considerably).

> Head clear. Mouth shut. See much. Say little.

*Roland Deschain, The Dark Tower V*

Summarizes one of my stronger beliefs in how to manage most life-situations as 
strategically as possible: when you don't know, it's best to just shut up and 
pay attention. Period.

> Long days, pleasant nights

*Roland Deschain, The Dark Tower I*

No particular clever comment on this one, but it's a really nice phrase to use!

> 'The world has moved on,' we say... we've always said. But it's moving on 
faster now. Something has happened to time. It's softening.

*Roland Deschain, The Dark Tower I*

Such elegant choice of words that create a mysterious yet nice feeling! 
Is Time really softening in our world today? Who is to say?!

> Trial of Humanity: The Defense rests. 

*Sensui, Yu Yu Hakusho*

This phrase brings up scenes from wars, etc. - so many people have fallen for 
the stupidity of war and wrong ideals. I also kinda feel that I use this phrase
when there is nothing more I can do or say to change a situation that has already
happened. I *defended* as best as I could my opinion/position/whatever. Now I have 
to *rest* and it's something that every human *goes through* (the trial). It's
feels truly unescapable.

> Maybe we are not alone and have not been. “The click beetles in my backyard   
don’t notice that they’re surrounded by intelligent beings — namely my          
neighbors and me, but we’re here, nonetheless.”                                 
                                                                                
*Seth Shostak*                                                                  
                                                                                
Regarding the [Fermi paradox](https://en.wikipedia.org/wiki/Fermi_paradox), from an astronomer at the SETI institute. 
He thinks that the answer to the Fermi paradox might lie not in something complex, 
like time and distance, but in *perception*.

> History will be kind to me, for I intend to write it

*Winston Churchill*

Big man, big words.

> Those who cannot remember the past are condemned to repeat it

*George Santayana*

True that.

> You should never accept money you feel you haven't earned. If you do, you'll 
start to always take the easy way out... Anyway, no good ever comes out of 
drowning in wealth or power.

*Arataka Reigen, Mob Psycho*

> You are a sceptic!  
Never!  
What are you?  
To define is to limit!

*Lord Henry Wotton, from the "Picture of Dorian Grey"* 

More of an epigram than a quote!

> When I do good, I feel good. When I do bad, I feel bad. And that is my 
religion.

*Abraham Lincoln*

Nice quote on altruism.

> Go ahead, show me what you've got. But so you know, I'm not expecting much.

*Saitama to Monster King Orochi, One Punch Man*

This is what one feels (without actually saying it) when he is a master at 
something and someone else comes and acts more knowledgable/better/stronger. 
It can be generalized against anything, e.g. *life*: show me what you got, I 
don't expect too much though! (meaning that whatever life throws at me, it is 
not going to change how I act)

> Put people in the same room

*Martin Kuiper, Professor of Systems Biology*

> From -10 to +10, going to Mc Donald's, drinking mocha Frappuccino.

*Asmund Flobak, Oncologist & Researcher*

Asmund summarized here my state of mind at a certain point during my PhD. 
It's actually a deeper quote than it sounds: it refers to these periods in
someone's life where you have such good and bad moments at the same time, 
everything seems so far away from normal, average days.
If you think about it in a systems dynamics sort-of way, it's like living 
during a chaotic life-phase with many oscillations 

> You go into a river once (You can't step into the same river twice!)

*Asmund Flobak, Oncologist & Researcher*

My take on this: don't do things twice, don't repeat mistakes, etc.

