# Motivation {-}

> Maybe one of the trees we're looking at right now is the world's tallest.
Maybe we'll find it some day.
You have to keep going Steve.
Never give up.
There is so much more to explore, so much more waiting to be discovered.
Let's just keep moving, Steve, okay?

*The Wild Trees*, Richard Preston

Steve here has a breakdown, finally realizing that his marriage is not going to work out after all.
Upon hearing his friend's suicidal urges (Steve is thinking of free falling from the gigantic Redwood trees they were climbing), he advices him to never give up and think about the trees.
His friend's words ring so TRUE to me.
There is the great unknonwn out there, which is worth exploring.
Focus on that, focus on the work yet to be done, there is meaning to be found there.
That's at least a way to find your Way.

> "Young man," he said to me, "do you imagine that everything in my life goes 
smoothly? Do you suppose I have no troubles, never hesitate and lose confidence 
in myself? Do you really think faith is always equally strong? All of us have 
difficult moments; but this is life. Hold up your head, and keep on your 
appointed path."

*Leo Tolstoy to Rachmaninoff*

Rachmaninoff was in a depressed state of mind and hadn't composed anything 
during that period. These words should had help him get up on his feet, but 
work was just what Rachmaninoff was unable to do at that time.

> Success is the ability to go from failure to failure without losing your 
enthusiasm

*Winston Churchill*

Common pattern. Wins are hard gained (no pain, no gain philosophy).

> I'd Rather Die Than Be A Loser

*Tom "The Golden Eagle" Platz*

> There is always 5 more!

*Tom "The Golden Eagle" Platz*

From the father of Squats, talking about reps.

> Be the change you want to see in the world

*Gandhi* (maybe)

> Be legendary

*Andreas Polimenis*

> I live only by the hopes of the future

Alexander Scriabin, Artist and Mystic (Biography)
