# Music {-}

> It is a very difficult piece. Now pianists don't feel shame playing difficult pieces very poorly.

Kapustin, *Conversations with Nikolai Kapustin*

Speaking of Prokofiev's Piano Concerto No. 1 that he played when he was 17 years old.

> A skilled musician literally "forgets" in the sense that he does not think about the delibarations that were involved in learning a piece of music.
In effect, he just says "go" and it happens.
Paradoxically, the more he "forgets" in this sense the more he is in control of what he is playing.

Denis Noble, *The Music of Life*

The author speaks here of the Taoist philosophy of "forgetting", which has similar manifestations in Buddhism and Chinese philosophy among others.
Simply put, it is about becoming one with the instrument and the music itself, becoming self-less.
Letting go.

> All languages are prisons of culture as well as liberators of communication.

Denis Noble, *The Music of Life*

Language precedes thought on many levels and thus it bears traps for the untrained mind.
The author suggests that the "self" or "I" is a concept deeply embedded in Western languages, whereas in Eastern languages (Korean, Japanese, Chinese) the focus is more on the verb/action/process and less on the subject/object/thing.
Western thought performs mental gymnastics to identify in which part of the brain is the self (which neural maps are associated with the concept of self) while Eastern thought and culture is more about becoming, being, and the process of life itself.
So it focuses on what is happening and not about who does the thinking (Descartes's *Cogito ergo sum*).

What I also liked from Denis's book (a keeper) is **the metaphors of the CD and the sheet music**. 
The genome is the thing which is written down in each case (digital bits or notes).
But just the CD or the sheet music is not the music itself, just as the DNA sequence on its own is not life.
It's the notes + you who play and interpret them + your emotions at that point in time + the piano + ... everything integrated (networks) that constitutes music.

> "Radio is not perfect enough really to do justice to good music," he said.
"That is why I have steadily refused to play for it. But my chief objection is
on other grounds.  
"It makes listening to music too comfortable. You often hear people say, 'Why 
should I pay for an uncomfortable seat at a concert when I can stay at home 
and smoke my pipe and put my feet up and be perfectly comfortable?'  
"I believe one shouldn't be too comfortable when listening to really great 
music. To appreciate good music, one must be mentally alert and emotionally 
receptive. You can't be that when you are sitting at home with your feet on a 
chair.   
"No, listening to music is more strenuous than that. **Music is like poetry;
it is a passion and a problem**. You can't enjoy and understand it merely by 
sitting still and letting it soak into your ears."

*Rachmaninoff (from an interview in Paris, 1928)*

Something that I also realized later in life: it's good to know that many share
the same opinion.

> "The poet Heine once said, **'What life takes away, music restores.'** He 
would not be moved to say this if he could hear the music of today. For the 
most part it gives nothing. **Music should bring relief**. It should 
rehabilitate minds and souls, and modern music does not do this. If we are to 
have great music we must return to **the fundamentals which made the music of 
the past great**. Music cannot be just color and rhythm; it must reveal the 
emotions of the heart."

*Rachmaninoff (from an interview for The New York Times, 1932)*

> **What is music!?** How can one define it? Music is a calm moonlight night, a 
rustling of summer foliage. Music is the distant peal of bells at eventide! 
**Music is born only in the heart** and it appeals only to the heart; it is 
Love! The sister of Music is Poesy, and its mother is Sorrow!

*Rachmanoninoff (1932)*

> His value and power as a pianist and conductor reside in his imagination, in
his inner perception of the original musical image. HIs performance is always
creative, always as if the composer were playing it - and always as if it were
**"for the first time". He seems to be improvising, making a song not heard
before...**

*Medtner to Rachmaninoff (1933)*

One of the most important qualitites of piano playing: whenever you play 
something that someone else wrote, play it like its the first time, like an 
improvisation. I believe this is what distinguishes really good classical music 
piano players.

