# Talent vs Genius? {-}

> No amount of genius can overcome obsession with detail.

*Anonymous*

Cannot be more true than that!

> "Can an ordinary person imagine things the way you do?"  
"You ask me if an ordinary person, by studying hard, would get to be able to 
imagine these things, like I imagine. Of course! I was an ordinary person who 
had studied hard. There are no miracle people. It just happen they got 
interested in these things and they learned all these stuffs. There are just 
people. **There's no talent, special, miracle ability to understand quantum 
mechanics** or a miracle ability to imagine electromagnetic fields that comes 
without practicing and reading and learning and studying, so if you say it 
take an ordinary person who's willing to devote a great deal of time and study 
and work and thinking in mathematics, then he has become a scientist."

*Richard Feynman*  

> I have no special talent. I am only passionately curious.

*Albert Einstein*

> If others would think as hard as I did, then they would get similar results.

*Newton*

> Doing easily what others find difficult is talent; doing what is impossible 
for talent is genius.

*Henri Frederic Amiel*

> "I am inclined to believe that **heredity** and **training** are inseparable and indispensable in any ART achievement. 
I consider that a capacity for hard work is also a Talent, and only those few artists who have inherited both musical and working talents attain the highest peak of their profession."

*Rachmaninoff (1937)*
